### ISSUE TITLE
Choose a maps API/package

### ISSUE THREAD

**Issue by costanza13** [costanza13/cool-california#3]
Possible solutions:
* https://www.npmjs.com/package/@googlemaps/google-maps-services-js
* https://www.npmjs.com/package/googlemaps

**Comment by jeff-follestad** [comment]
![Screen Shot 2021-06-26 at 2 12 55 PM](https://user-images.githubusercontent.com/78771614/123525840-9b0aba80-d688-11eb-8845-9d8dbc23388c.png)

**Comment by jeff-follestad** [comment]
Michael, I grabbed the Maps API issue, set up a GCP account, got a Google Maps API key, and am doing some testing.

![Screen Shot 2021-06-26 at 2 14 28 PM](https://user-images.githubusercontent.com/78771614/123525868-d0170d00-d688-11eb-926a-b07a25fef27e.png)

**Comment by costanza13** [comment]
@jeff-follestad - Sorry, I hadn't seen this before.  Let me know if you want to swap in your credentials.

Closing this issue as we decided to go with the "googlemaps" package https://www.npmjs.com/package/googlemaps
